name: strends
channels:
  - https://repo.anaconda.com/pkgs/free
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - attrs=19.1.0
  - babel=2.7.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.0
  - bleach=3.1.0
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cffi=1.12.3
  - colorama=0.4.1
  - cryptography=2.5
  - decorator=4.4.0
  - defusedxml=0.5.0
  - docutils=0.15.2
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - icu=58.2=vc14_0
  - idna=2.8=py37_1000
  - imagesize=1.1.0
  - intel-openmp=2019.3=203
  - ipykernel=5.1.2
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jdcal=1.4
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.2
  - jupyter_client=5.3.1
  - jupyter_core=4.4.0
  - keyring=19.0.2
  - krb5=1.16.3
  - lazy-object-proxy=1.4.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.37
  - libpq=10.6
  - libsodium=1.0.17
  - libxml2=2.9.9
  - libxslt=1.1.32
  - lxml=4.4.1
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.3=203
  - numpy=1.16.2
  - numpydoc=0.9.1
  - openpyxl=2.5.12
  - openssl=1.0.2r
  - packaging=19.0
  - pandas=0.23.4
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pickleshare=0.7.5
  - pip=19.0.3
  - prompt_toolkit=2.0.9
  - psycopg2=2.7.5
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pygments=2.4.2
  - pylint=2.3.1
  - pyodbc=4.0.24
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.6.0
  - pyrsistent=0.15.4
  - pysocks=1.6.8
  - python=3.7.1
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pywin32-ctypes=0.2.0
  - pyzmq=18.0.2
  - qt=5.6.2
  - qtawesome=0.6.0
  - requests=2.21.0
  - setuptools=41.0.0
  - sip=4.18.1
  - six=1.12.0
  - snowballstemmer=1.9.0
  - soupsieve=1.9.2
  - sqlalchemy=1.2.14
  - sqlite=3.29.0
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.2
  - urllib3=1.24.2
  - vc=14=0
  - vs2015_runtime=14.0.25420
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.11.2
  - xlrd=1.1.0
  - zeromq=4.3.2
  - zlib=1.2.11

