version: "3.1"

services:
     db:
         container_name: strends_psql
         image: postgres:10
         environment:
             POSTGRES_USER: usr
             POSTGRES_PASSWORD: pass
             POSTGRES_DB: strends 
         volumes:
             - db_data:/var/lib/postgresql/data
         ports:
             - 5432:5432/tcp
 
volumes:
    db_data: