version: '3.1'

services:
     db:
         image: kiasaki/alpine-postgres
         environment:
             POSTGRES_USER: foo
             POSTGRES_PASSWORD: bar
             POSTGRES_DB: faz 
         volumes:
             - db_data:/var/lib/postgresql/data
         ports:
             - 5432:5432/tcp
 
volumes:
    db_data:
         driver: local